DWPF-1041 Clean up "Yes" options
uktrade/irap pull request #122
Opened 2023-11-27 16:03 UTC by CamLamb

2023-11-29 09:49 UTC, CamLamb commented on core/forms/irap_request.py
> +    for choice in choices:
Marcel has told me about the model ordering that is already set up so I will refactor to use that instead of bringing these to the bottom in the form

2023-11-29 09:56 UTC, SamDudley requested changes

2023-11-29 09:56 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +    for model_class in NEW_REFERENCE_DATA_MODEL_OPTIONS.keys():
`.keys()` is redundant here

2023-11-29 09:56 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +        SpecificReferenceDataModel.objects.all().delete()
you are deleting all the data so this isn't a reverse

2023-11-29 09:56 UTC, SamDudley commented on core/templates/core/irap_request/steps/classification.html
>      {% include './form_footer.html' %}
not sure why you have added a second form footer

2023-11-29 09:56 UTC, SamDudley commented on core/templates/core/irap_request/steps/cyber_authentication.html
> +        {% gds_field form.can_enable_multi_factor_auth template='gds/radio.html' conditionals=True hide_label=True divider='or' %}
no need for the indent - i'm guessing you have djlint running - you might want to turn it off for this project ;)

2023-11-29 09:56 UTC, SamDudley commented on core/templates/core/irap_request/steps/cyber_downloads.html
> +        {% gds_field form.cyber_downloads template='gds/checkboxes.html' hide_label=True conditionals=True divider='or' %}
same as above

2023-11-29 09:56 UTC, SamDudley commented on core/templates/core/irap_request/steps/cyber_software.html
> +        {% gds_field form.cyber_software template='gds/checkboxes.html' hide_label=True divider='or' %}
i'll stop pointing these out but the indent changes are unecessary

2023-11-29 10:59 UTC, SamDudley requested changes

2023-11-29 10:59 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +            )
you need to get the max not the last

2023-11-29 10:59 UTC, SamDudley commented on core/templates/gds/_options.html
> +    divider_location (str): The location to insert the divider (default: 1 from end).
you called it divider_offset

2023-11-29 10:59 UTC, SamDudley commented on core/templates/gds/_options.html
> -
revert formatting changes in this file

2023-11-29 10:59 UTC, SamDudley commented on core/templatetags/gds.py
> +        "divider_location": divider_location,
not sure about the rename here. it adds a layer of indirection

2023-11-29 10:59 UTC, SamDudley commented on core/templatetags/gds.py
> +    divider_offset = kwargs.get("divider_offset", 1)
it would feel more pythonic if the offset was negative to insert from the end, like how you index into a list, e.g. -1, -2

2023-11-29 11:08 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +            )
cam pointed out we set a default ordering so you can ignore this comment

2023-11-29 13:36 UTC, CamLamb commented on core/templates/gds/_options.html
> +    divider_location (str): The location to insert the divider (default: 1 from end).
The template tag arg is `divider_offset` the context has `divider_location`. One to discuss it seems :D

2023-11-30 16:58 UTC, SamDudley requested changes

2023-11-30 16:58 UTC, SamDudley commented on core/forms/utils.py
> +    "Don't know".
this reads like the function will check if they have selected those options together when it also covers if they have selected them with another option

2023-11-30 16:58 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +from core.constants import YesNoDontKnowChoices, YesNoneDontKnowChoices
remove dependency on app code which could change

2023-11-30 16:58 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +        no_pd_request.types_of_personal_data.set(
i think this needs to be `add` not `set` - won't set remove other options?

https://docs.djangoproject.com/en/4.0/ref/models/relations/#django.db.models.fields.related.RelatedManager.set

2023-11-30 16:58 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +        dont_know_pd_request.types_of_personal_data.set(
see above

2023-11-30 16:58 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +        no_sc_request.personal_data_special_categories.set(
see above

2023-11-30 16:58 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +        dont_know_sc_request.personal_data_special_categories.set(
see above

2023-11-30 16:58 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +        no_dp_request.data_processes.set([IrapRequest.PersonalData.NONE_OF_THE_ABOVE])
see above

2023-11-30 16:58 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +        dont_know_dp_request.data_processes.set([IrapRequest.PersonalData.DONT_KNOW])
see above

2023-11-30 16:58 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +            update_fields.append("has_personal_data")
where do we set it to "Yes" if we do have `types_of_personal_data`

2023-11-30 16:58 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +            update_fields.append("has_special_categories")
see above

2023-11-30 16:58 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +            irap_request.save(update_fields=update_fields)
see above

2023-11-30 16:58 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +            irap_request.has_personal_data = has_special_categories
assigning to wrong field

2023-11-30 16:58 UTC, SamDudley commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +            irap_request.has_personal_data = has_data_processes
assigning to wrong field

2023-11-30 16:58 UTC, SamDudley commented on core/templates/gds/_options.html
> +<div class="govuk-{{ govuk_class }}{% if inline %} govuk-{{ govuk_class }}--inline{% endif %}"
reset any djlint formatting

2023-11-30 16:58 UTC, SamDudley commented on core/templates/gds/_options.html
> +    divider_location (str): The location to insert the divider (default: 1 from end).
isn't this an int?

2023-11-30 16:58 UTC, SamDudley commented on core/templates/gds/_options.html
> -            <label class="govuk-label govuk-{{ govuk_class }}__label" for="{{ option.id_for_label }}">
reset djlint formatting (check rest of file)

2023-11-30 16:58 UTC, SamDudley commented on core/templatetags/gds.py
> +    }
reset formatting change

2023-12-01 09:24 UTC, CamLamb commented on core/migrations/0127_update_reference_data_with_i_dont_know.py
> +        no_pd_request.types_of_personal_data.set(
It is set because if we select "None of the above" or "I don't know" then those should be the only options that are selected. It wouldn't make sense to have "None of the above" AND something from above selected

2023-12-01 09:26 UTC, CamLamb commented on core/templatetags/gds.py
> +            pass
This feels a little clunky, especially since the only thing we are protecting against by adding this is a developer that adds the value without checking if it made the expected change.

2023-12-01 09:30 UTC, CamLamb commented on core/templatetags/gds.py
> +            context.update(divider_location=divider_location)
I would say that the right thing would probably be to do this only if a "divider" is set as this defines the default behaviour so you can add a divider and not have to define an offset in most cases.

2023-12-01 09:59 UTC, SamDudley requested changes

2023-12-01 13:46 UTC, SamDudley approved these changes

2023-12-01 13:51 UTC, merged