DWPF-1044 Redirection to requests page if active requests are present
uktrade/irap pull request #123
Opened 2023-11-27 17:15 UTC by nicopicchio

2023-12-06 14:26 UTC, SamDudley requested changes

2023-12-06 14:42 UTC, CamLamb commented
Adding some notes here. @nicopicchio I'll reach out and we can go through the remaining work together.

### Tests

Update the homepage tests to test for the following scenarios:

- [ ] As an IRAP Secretariat, When I visit the homepage I am redirected to the IRAP Request list
- [ ] As an IRAP Requestor, When I visit the homepage I am redirected to the IRAP Request list
- [ ] As an IRAP Collaborator, When I visit the homepage I am redirected to the IRAP Request list
- [ ] As a logged in user (none of the above), When I visit the homepage I am redirected to the Getting Started page

### Code changes

- [ ] Update the home view to meet the above test scenarios
- [ ] Remove the permission check from `user_is_related_to_irap_requests` and check that in the home view

2023-12-07 12:32 UTC, CamLamb commented on tests/conftest.py
> +def irap_request(db):
Just been chatting about this with Sam and we think it should be renamed to `irap_request_for_another_user`

And a new fixture created called `another_user` instead of `user = User.objects.get(username="ulani.user")`

2023-12-07 13:32 UTC, CamLamb approved these changes
Great work! LGTM!

2023-12-07 15:33 UTC, merged