Messages app and initial notification display
uktrade/irap pull request #124
Opened 2023-11-30 15:31 UTC by marcelkornblum

A new Django app for Persistent Messages
Almost standalone / able to be reused though will need a little work to make that work.
App is also integrated into the core IRAP requests app, with template overrides and some functionality removed for now, but more irap business logic applied.
Overall structure is Object (Irap request) -> Message -> Notification -> User. Notification can be read or unread. Message can be resolved or not.
Presents a list of minimal notification items, and an "inbox" UI using the list and a details view
list is presented next to the task-list view, and inbox per irap request. Also unread messages surfaced on the list of requests view.

*NB does not actually implement any auto notifications in the project*

2023-12-05 16:41 UTC, CamLamb commented on core/services/messages.py
> +    )
I think consolidating `{"irap_request": irap_request}` into a dict above this would be nice, maybe something like `message_context = {"irap_request": irap_request}`?

2023-12-05 16:41 UTC, CamLamb commented on core/services/messages.py
> +    send_alerts = bool(TEMPLATED_MESSAGES[type_code]["send_alerts"])
What if this key doesn't exist?
When would this key exist?

2023-12-05 16:58 UTC, marcelkornblum commented on core/services/messages.py
> +    )
good call

2023-12-05 16:59 UTC, marcelkornblum commented on core/services/messages.py
> +    send_alerts = bool(TEMPLATED_MESSAGES[type_code]["send_alerts"])
Sam probaby doesnt want this in at all. I thought itd be useful to stub for the future and assumed we'd be good to force it in but have just made it more permissive

2023-12-06 12:19 UTC, marcelkornblum commented on core/services/messages.py
> +TEMPLATED_MESSAGES = {
type this dict

2023-12-06 12:20 UTC, marcelkornblum commented on core/services/messages.py
> +    if type_code not in TEMPLATED_MESSAGES.keys():
```suggestion
    if type_code not in TEMPLATED_MESSAGES:
```

2023-12-06 12:23 UTC, marcelkornblum commented on core/services/messages.py
> +    )
TEMPLATED_MESSAGES[type_code].get("send_alerts", False)

2023-12-06 12:35 UTC, marcelkornblum commented on core/templates/core/irap_request/partials/display.html
> +<h1 class="govuk-heading-m">Your request</h1>
undo

2023-12-06 12:37 UTC, marcelkornblum commented on core/templates/core/irap_request/task_list.html
> +            {% if message_list|length == 0 %}
```suggestion
            {% if message_list %}
```
switch if/else around

2023-12-06 12:41 UTC, marcelkornblum commented on core/templates/persistent_messages/partials/detail.html
> +    {% comment %} <div class="govuk-button-group" hx-boost="true" hx-target="#list-item-{{ message.pk }}" hx-swap="outerHTML">
remove

2023-12-06 17:15 UTC, SamDudley requested changes

2023-12-06 17:15 UTC, SamDudley commented on persistent_messages/templatetags/persistent_messages.py
> +        "unread_messages": get_messages_for_user(
doesn't seem to match the use of `messages` in the template?

2023-12-06 17:15 UTC, SamDudley commented on persistent_messages/views.py
> +    """
```suggestion
    """Render the full inbox with the given message selected."""
```

2023-12-06 17:15 UTC, SamDudley commented on persistent_messages/views.py
> +@require_GET
Am I right in thinking we are adding some code here that isn't used as we defined out own version in core?

2023-12-06 17:15 UTC, SamDudley commented on persistent_messages/views.py
> +    Looks for a custom header to decide whether to treat the response as async
nit pick: not sure on the word `async`, think the key word is `partial`

2023-12-06 17:15 UTC, SamDudley commented on tests/core/services/test_messages.py
> +    def setUp(self, db, user):
personal: `_setup` > unittest idioms

2023-12-06 17:15 UTC, SamDudley commented on tests/core/services/test_messages.py
> +    def test_send_templated_message(self, mocker):
discussion: do we need all the mocking? why can't we write a scenario and check the messages and notifications models?

2023-12-06 17:15 UTC, SamDudley commented on tests/persistent_messages/test_models.py
> +        assert Message.objects.unread_by_user(brenda).count() == 0
personal: i like to place comments through my scenario to place anchors as to what's going on

2023-12-06 17:32 UTC, marcelkornblum commented on core/services/messages.py
> +TEMPLATED_MESSAGES: dict[str, MessageTemplate] = {
I surprised myself - I really did!

2023-12-06 17:35 UTC, marcelkornblum commented on persistent_messages/views.py
> +@require_GET
yes you are

in this case the one here still handles filtering and stuff that the core one doesn't, and this one doesn't work with the "inbox per object" approach that we took, but I was loathe to delete it.

There's a bit more of that around the place - the state change handlers (views, services, etc) and the context_processor come to mind.

2023-12-07 09:15 UTC, marcelkornblum commented on tests/core/services/test_messages.py
> +    def test_send_templated_message(self, mocker):
mocking is how you do unit tests. I think we should have both unit and scenario; not that I've been especially consistent here. However, I believe yes you do need all the mocking and unit tests have a value not shared by scenario tests (and vice versa)

2023-12-11 09:21 UTC, SamDudley requested changes

2023-12-11 09:21 UTC, SamDudley commented on core/views/irap_request.py
> +    Overwirte package view for inbox that's request-specific and will less logic
```suggestion
    Overwirte package view for inbox that's request-specific and with less logic.
```

2023-12-11 09:21 UTC, SamDudley commented on core/views/irap_request.py
> +        if request.user.pk not in message.notifications.values_list("user", flat=True):
I think by this point `notifications` have been fetched using `prefetch_related`?

If that's true then I don't *think* this will cause an additional query and it's fine. However, if it isn't then a `filter().exist()` query would be more efficient?

2023-12-11 09:21 UTC, SamDudley commented on frontend/src/messages.js
> +        console.log("found it!", element);
I don't think we need to keep the `console.log`.

2023-12-11 09:21 UTC, SamDudley commented on tests/core/services/test_messages.py
> +    def test_send_templated_message(self, mocker):
Discussed offline.

2023-12-11 09:22 UTC, marcelkornblum commented on core/views/irap_request.py
> +        if request.user.pk not in message.notifications.values_list("user", flat=True):
they should have, because of going via the service which adds that in

2023-12-11 09:23 UTC, marcelkornblum commented on frontend/src/messages.js
> +        console.log("found it!", element);
oops

2023-12-11 10:35 UTC, SamDudley commented on persistent_messages/models.py
> +        # can't chain the filters or they work as OR
https://docs.djangoproject.com/en/5.0/topics/db/queries/#spanning-multi-valued-relationships

2023-12-11 10:35 UTC, SamDudley approved these changes

2023-12-11 11:02 UTC, merged