DWPF-1110 Removing cyber-supporting-documents form
uktrade/irap pull request #134
Opened 2023-12-08 15:26 UTC by nicopicchio

2023-12-11 09:38 UTC, SamDudley requested changes
Great job! Be careful with auto formatters generating lots of unnecessary changes.

2023-12-11 09:38 UTC, SamDudley commented on core/fixtures/test_irap_requests.json
> +]
It looks like these are only formatting changes. In future please be careful with auto formatting as it adds noise to the diff and make it harder to review changes.

In this case there aren't too many changes, but on a large file it can be very difficult to review. I would suggest learning your editor's shortcut for `save without format` if you see that a lot of lines will be changed.

2023-12-11 09:38 UTC, SamDudley commented on core/templates/core/irap_request/partials/display.html
> -
Here is another example of a large diff caused by auto formatting changes. In this case I would like you to revert any formatting only changes as the blank lines help group the fields.

2023-12-11 09:38 UTC, SamDudley commented on core/templates/core/irap_request/partials/display.html
> -            {% field 'cyber_supplier_website' 'core:request:cyber-supporting-documents' %}
For guidance, these should be the only lines changed in this file.

2023-12-12 09:59 UTC, nicopicchio commented on core/fixtures/test_irap_requests.json
> +]
yeah, sorry about that, I did not realised it even happened, otherwise I would discarded the changes on the file and reapplied. I'm guessing it's prettier since it's a json file but I cannot recall changing anything on this file and I don't know why prettier would run on it. I'll look into the save without format option. thank you.

2023-12-12 13:29 UTC, SamDudley approved these changes
Great work!

2023-12-12 13:30 UTC, merged