DWPF-1164 Update cyber-downloads form
uktrade/irap pull request #172
Opened 2024-01-09 10:16 UTC by 0RWilliams

2024-01-09 11:33 UTC, 0RWilliams commented
For review: I had key errors with previous ref data added in 107. see 147, was this overkill?

2024-01-09 11:44 UTC, SamDudley requested changes
There are a couple of issues with the migration. Please message me if you have any questions or issues.

2024-01-09 11:44 UTC, SamDudley commented on core/migrations/0147_cyber_downloads_modify.py
> +    remove_reference_data(apps, schema_editor)
Some of these haven't change and the options should be preserved and migrated instead of deleted.

- if the `code` already exists, update the `name`
- if it's a new `code`, insert a new row
- remove any existing rows which don't have a matching `code` above
- set the order of the options to match the order of `OPTIONS` above

2024-01-09 11:44 UTC, SamDudley commented on core/migrations/0147_cyber_downloads_modify.py
> +    SpecificReferenceDataModel.objects.all().delete()
This is not a valid reverse function, it does not put the data back into the state it was before this migration was ran. It will not be possible to have a reverse function for this migration as we will lose information we don't retain. Please remove the reverse function from the `RunPython` call.

2024-01-10 13:58 UTC, SamDudley approved these changes

2024-01-10 13:58 UTC, SamDudley commented on core/fixtures/test_irap_requests.json
> +        "xls","csv"
```suggestion
        "xls",
        "csv"
```

2024-01-10 13:58 UTC, SamDudley commented on core/models.py
> +        jpeg_png = "jpeg_png"
```suggestion
        JPEG_PNG = "jpeg_png"
```

2024-01-10 13:58 UTC, SamDudley commented on core/migrations/0148_cyber_downloads_modify.py
> +        name="Image formats (i.e. jpg, png)"
```suggestion
        name="Image formats (i.e. .jpg, .png)"
```

2024-01-10 13:58 UTC, SamDudley commented on core/migrations/0148_cyber_downloads_modify.py
> +        code="xlsm_docm", name="Macro enabled (.xlsm, .docm)"
```suggestion
        code="xlsm_docm", name="Macro enabled (i.e. .xlsm, .docm)"
```

2024-01-10 14:33 UTC, merged