526: cyber downloads page
uktrade/irap pull request #79
Opened 2023-09-06 15:54 UTC by marcelkornblum

2023-09-06 20:30 UTC, SamDudley requested changes

2023-09-06 20:30 UTC, SamDudley commented on core/migrations/0107_cyber_download.py
> +    ("jpeg-png", ".jpeg / .png"),
What do you think to these being snake case? Rational is that makes them valid python names and would match our `TextChoices`.

2023-09-06 20:30 UTC, SamDudley commented on core/models.py
> +        null=True,
I checked earlier and you don't need `null=True` on `ManyToManyField` it has no effect.

2023-09-06 20:30 UTC, SamDudley commented on core/templates/core/irap_request/steps/downloads.html
> +        utils.exclusiveCheckboxOption("{{ form.cyber_downloads.html_name }}", "none_of_the_above");
Should be `"not_applicable"`

2023-09-07 07:56 UTC, marcelkornblum commented on core/migrations/0107_cyber_download.py
> +    ("jpeg-png", ".jpeg / .png"),
yes totally makes sense

2023-09-07 07:57 UTC, marcelkornblum commented on core/templates/core/irap_request/steps/downloads.html
> +        utils.exclusiveCheckboxOption("{{ form.cyber_downloads.html_name }}", "none_of_the_above");
d'oh!

2023-09-07 08:05 UTC, SamDudley approved these changes

2023-09-07 14:47 UTC, merged